theme = 'pehtheme-hugo'
baseURL = 'https://pehtheme-ads.netlify.app/'
languageCode = 'en-us'
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableRobotsTXT = true
title = 'RocketMyAds'

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = '' # <- Your GA-4
disqusShortname = '' # <- Get form here : https://disqus.com

[pagination]
  pagerSize = 6 # <- Set the desired number of posts per page

[menu] # Menu management
  # [[menu.main]]
  #   name = 'Home'
  #   pageRef = '/'
  #   weight = 10
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 15
  [[menu.main]]
    name = 'Contacts'
    pageRef = '/contacts'
    weight = 20
  # [[menu.main]]
  #   name = 'Taxonomy'
  #   pageRef = '/tags/space/'
  #   weight = 25

[sitemap]
  changefreq = "weekly"
  disable = false
  filename = "sitemap.xml"
  priority = 0.8

[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"