[hugoVersion]
  extended = false
  min = "0.147.9"
  max = ""
[[mounts]]
  source = "static"
  target = "static"
## assets
[[mounts]]
  source = "node_modules/@thulite/images/assets"
  target = "assets"
[[mounts]]
  source = "assets"
  target = "assets"
## layouts
[[mounts]]
  source = "node_modules/@thulite/images/layouts"
  target = "layouts"
[[mounts]]
  source = "layouts"
  target = "layouts"